--- 
abstract: escape continuations (returning higher up the stack)
author: 
  - Shawn M Moore <sartak@bestpractical.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: Continuation-Escape
requires: 
  Scalar::Util: 1.19
  Scope::Upper: 0.05
  Test::Exception: 0.27
version: 0.01
